{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      ../modules/default.nix
      (modulesPath + "/profiles/qemu-guest.nix")
    ];
	## IMPORT OF HARDWARE CONFIGURATION

	# Do not modify this file!  It was generated by ‘nixos-generate-config’
	# and may be overwritten by future invocations.  Please make changes
	# to /etc/nixos/configuration.nix instead.

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8382b557-4317-433c-9bd7-4bcbe7340bcd";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/996bd327-e012-4f7c-937c-ace8c98540af"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

	## END OF IMPORT OF HARDWARE CONFIGURATION
  nixpkgs.config.allowUnfree = true; # Plex is unfree

	## Networking

	#open port for paperless
	networking.firewall.allowedTCPPorts = [ 28981 ];

  ###SHELL
  programs.zsh.enable = true;
  users.defaultUserShell = pkgs.zsh;

  ###OS TOOLS
  nix.settings.experimental-features = ["nix-command" "flakes"];
  environment.systemPackages = with pkgs; [
    git
    curl
    zip
    unzip
    wget
    screen
    nmap
    traceroute
    cifs-utils
  ];
  ### CLOUD
  cloud = {
    enable = true;
  };
  ### SSH
  sshmodule = {
    enable = true;
    port = [55];
  };

  # Use the systemd-boot EFI boot loader.
  #boot.loader.systemd-boot.enable = true;
  #boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.grub.enable = true;
  boot.loader.grub.device = "/dev/sda";

  networking = {
    hostName = "cOS"; # Define your hostname.
#    nameservers = ["1.1.1.1" "1.0.0.1"];
#    interfaces.ens18.ipv4.addresses = [{
#      address = "192.168.5.122";
#      prefixLength = 16;
#    }];
#    defaultGateway = {
#      address = "192.168.4.1";
#	    interface = "ens18";
#	  };
  };

  fileSystems."/run/media/familyvault" = {
    device = "//192.168.5.114/familyvault";
		fsType = "cifs";
		options = [
			"credentials=/data/.secret/smb.txt"
			"iocharset=utf8"
			"vers=3.1.1"
			"nofail"
			"forcegid"
			"dir_mode=0777"
			"file_mode=0777"
			"gid=vault"
			"x-systemd.automount"
		];
	};

  # Set your time zone.
  time.timeZone = "US/Michigan";

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users.lalobied = {
    isNormalUser = true;
    home = "/home/lalobied";
    extraGroups = [ "wheel" "vault" ]; # Enable ‘sudo’ for the user.
  };

  system.stateVersion = "25.05";
}
